services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb

    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: posc

    volumes:
      - db:/data/postgres



volumes:
  db: