// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_create_deck from "./routes/api/create/deck.ts";
import * as $api_create_performance from "./routes/api/create/performance.ts";
import * as $api_create_question from "./routes/api/create/question.ts";
import * as $api_create_session from "./routes/api/create/session.ts";
import * as $api_list_deck from "./routes/api/list/deck.ts";
import * as $api_list_tag from "./routes/api/list/tag.ts";
import * as $index from "./routes/index.tsx";
import * as $session_index from "./routes/session/index.tsx";
import * as $Home from "./islands/Home.tsx";
import * as $Question from "./islands/Question.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/create/deck.ts": $api_create_deck,
    "./routes/api/create/performance.ts": $api_create_performance,
    "./routes/api/create/question.ts": $api_create_question,
    "./routes/api/create/session.ts": $api_create_session,
    "./routes/api/list/deck.ts": $api_list_deck,
    "./routes/api/list/tag.ts": $api_list_tag,
    "./routes/index.tsx": $index,
    "./routes/session/index.tsx": $session_index,
  },
  islands: {
    "./islands/Home.tsx": $Home,
    "./islands/Question.tsx": $Question,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
